README.md
example.conf
gitkanban/__init__.py
gitkanban/exceptions.py
gitkanban/gitkanban.py
setup.py

#1 implemented ensure-labels feature

---

gitkanban/constarints_state.py
gitkanban/exceptions.py
gitkanban/gitkanban.py
setup.py

#3 implemented new_constraint feature

---

gitkanban/constarints_state.py
gitkanban/gitkanban.py

#5 added logs and metrics

---

gitkanban/gitkanban.py

#5 updated alert msg and added desc to constraint

---

gitkanban/gitkanban.py

#29 re-organised the check_constraints cmd

---

gitkanban/constarints_state.py
gitkanban/gitkanban.py

#24 implemented auto-resolve for issue move from one queue to another queue

---

gitkanban/gitkanban.py

#28 resolved manual auto-resolve issue

---

gitkanban/constarints_state.py
gitkanban/exceptions.py
gitkanban/gitkanban.py
setup.py

#25 implemented multiple assignees to a single alert

---

gitkanban/gitkanban.py

#36 resolved re-open a manual closed alert

---

gitkanban/gitkanban.py

#41 supported multiple constraint formats

---

gitkanban/gitkanban.py

#44 resolved a bug to delete record in db

---

gitkanban/gitkanban.py

#47 resolved repo_group_label bug.

---

gitkanban/constarints_state.py
gitkanban/gitkanban.py

#9 implemented escalation hierarchy logic

---

gitkanban/gitkanban.py

#49 resolved getting alerts in weekends.

---

gitkanban/constarints_state.py
gitkanban/gitkanban.py

#9 resolved bugs in escalation

---

gitkanban/gitkanban.py

#58 supported alert title form config file

---

gitkanban/gitkanban.py

#9 handled properly

---

gitkanban/gitkanban.py

#69 resolved multiple alerts for the same issue

---

gitkanban/gitkanban.py

#40 implemented retry logic for failed url

---

gitkanban/gitkanban.py

#33 implemented handling pull requests issues perfectly

---

gitkanban/gitkanban.py

#77 resolved weekend alert bug

---

gitkanban/gitkanban.py

#51 implemented snooze feature

---

gitkanban/gitkanban.py

#51 moved global variables to config file

---

gitkanban/gitkanban.py

#51 implemented label logic

---

gitkanban/gitkanban.py

#51 get snooze label from higher level of config file

---

gitkanban/constraints_state.py
gitkanban/gitkanban.py
setup.py

#99 resolved escalation hierarchy bug

---

gitkanban/gitkanban.py

#97 handled snooze feature as per requested

---

gitkanban/gitkanban.py

#38 implemented auto un-assign feature

---

gitkanban/gitkanban.py
setup.py

#85 implemented logic for not to consider weekends and non working hours for evaluating constraints

---

gitkanban/gitkanban.py

#107 resolved new release bugs

---

gitkanban/gitkanban.py

#114 resolved escalation hierarchy bug

---

gitkanban/gitkanban.py

#109 implemented skip alerts on public holidays

---

gitkanban/gitkanban.py

#118 resolved NoneType error in snooze feature

---

gitkanban/gitkanban.py

#122 resolved snooze bug

---

gitkanban/gitkanban.py

#115 resolved unassign people from auto un-assign feature

---

gitkanban/gitkanban.py

#126 resolved snooze feature bug

---

gitkanban/gitkanban.py

#126 removed duplicate repositories check for snooze feature

---

gitkanban/gitkanban.py

#127 resolved escalation bug

---

gitkanban/gitkanban.py

#138 handled connection error while requesting a url

---

gitkanban/gitkanban.py

#130 implemented inbox logic

---

gitkanban/gitkanban.py

#130 resolved inbox bug

---

gitkanban/gitkanban.py

#129 send alert for agent assignees

---

gitkanban/gitkanban.py

#146 stop sending alerts for snooze issues

---

gitkanban/gitkanban.py

Removed check for .json file extension and allows for any extension for the config file.

references #134, Removed .json extension check

---

gitkanban/gitkanban.py

#113 implemented stop sending alerts during person off days

---

example.conf

#133 updated the example.conf file

---

gitkanban/gitkanban.py

#146 removed logic for snooze issues

---

example.conf
gitkanban/gitkanban.py

Custom work hours

---

gitkanban/gitkanban.py

#110 implemented send alerts for freshers upto 1year

---

gitkanban/gitkanban.py

#152 resolved inbox actual behaviour

---

gitkanban/gitkanban.py

#152 resolved inbox bug

---

gitkanban/gitkanban.py

#159 resolved pull request bug

---

gitkanban/gitkanban.py

#162 resolved people issue

---

gitkanban/constraints_state.py
gitkanban/gitkanban.py

#162 resolved inbox alerts auto resolved issue

---

gitkanban/gitkanban.py

#162 resolved pull request bugs

---

gitkanban/gitkanban.py

#162 resolved key error bug

---

example.conf
gitkanban/gitkanban.py

#136 implemented needs-update logic

---

.travis.yml

#12 using travis make a deploy and push to public pypi

---

Dockerfile

#13 added dockerfile

---

.travis.yml
docker_build_push.sh

#174 implemented to push dockerhub for every release via travis

---

.travis.yml
docker_build_push.sh

#174 added docker service to travis

---

gitkanban/gitkanban.py

#162 resolved key error

---

gitkanban/gitkanban.py

#162 resolved req params bug

---

gitkanban/gitkanban.py

#183 resolved delay of auto-resolve alerts

---

README.md
gitkanban/sync.py

comprehensive comments for each function and updated ``README.md``` to match new sub-commands and sub-sub commands.

added comments, update readme

---

gitkanban/gitkanban.py

#150 implemented not to consider timing for person public/off days
